openapi: 3.0.0

info:
  title: Booking Data Hotel BCA
  version: 1.0.0

tags:
  - name: API List

parameters:
  - name: room_id
    in: path
    description: Room ID to be deleted
    required: true
    type: integer

responses:
  200:
    description: Room deleted
  404:
    description: Room not found
