openapi: 3.0.0

info:
  title: Booking Data Hotel BCA
  version: 1.0.0

tags:
  - name: API List

definitions:
  Booking:
    type: object
    properties:
      booking_id:
        type: integer
      room_id:
        type: integer
      customer_name:
        type: string
      check_in_date:
        type: string
        format: date
      check_out_date:
        type: string
        format: date
      total_price:
        type: number

parameters:
  - name: booking_id
    in: path
    description: Booking ID
    required: true
    type: integer

responses:
  200:
    description: Booking Data by ID
    schema:
      $ref: '#/definitions/Booking'
  404:
    description: Booking not found
